"""Add findings table

Revision ID: 95b863796b86
Revises: 5aa971b2238a
Create Date: 2026-09-19 18:32:04.465220
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '95b863796b86'
down_revision: str | None = '5aa971b2238a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='finding_severity'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_key', sa.String(length=64), nullable=False),
    sa.Column('estimated_monthly_impact', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'rule_id', 'period', 'evidence_key', name='uq_finding_evidence')
    )
    op.create_index(op.f('ix_findings_user_id'), 'findings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_user_id'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
