"""initial schema

Revision ID: 71f63885b599
Revises:
Create Date: 2026-09-17 18:05:08.271735
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "71f63885b599"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "checking", "savings", "cash", "credit_card", "investment", name="account_type"
            ),
            nullable=False,
        ),
        sa.Column("opening_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("institution", sa.String(length=80), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_account_name"),
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.Enum("income", "expense", name="category_kind"), nullable=False),
        sa.Column(
            "essentiality",
            sa.Enum("essential", "important", "flexible", "optional", name="essentiality"),
            nullable=True,
        ),
        sa.Column("system", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "parent_id", "name", name="uq_category_name"),
    )
    op.create_index(op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column(
            "transaction_type",
            sa.Enum("income", "expense", "transfer", name="transaction_type"),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("merchant", sa.String(length=160), nullable=True),
        sa.Column("merchant_normalized", sa.String(length=160), nullable=True),
        sa.Column(
            "payment_method",
            sa.Enum(
                "cash",
                "debit",
                "credit",
                "pix",
                "boleto",
                "transfer",
                "other",
                name="payment_method",
            ),
            nullable=True,
        ),
        sa.Column("installment_number", sa.SmallInteger(), nullable=True),
        sa.Column("installment_count", sa.SmallInteger(), nullable=True),
        sa.Column("installment_group_id", sa.UUID(), nullable=True),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column("recurrence_group_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "paid", "overdue", "canceled", name="transaction_status"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "manual", "pdf", "xml", "json", "image", "ai_extraction", name="transaction_source"
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("transfer_peer_id", sa.UUID(), nullable=True),
        sa.Column(
            "transfer_direction",
            sa.Enum("outgoing", "incoming", name="transfer_direction"),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(transaction_type = 'transfer') = (transfer_direction IS NOT NULL)",
            name="ck_transaction_transfer_direction",
        ),
        sa.CheckConstraint("amount > 0", name="ck_transaction_amount_positive"),
        sa.CheckConstraint(
            "installment_count IS NULL OR installment_number <= installment_count",
            name="ck_transaction_installments",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transactions_dedup",
        "transactions",
        ["user_id", "merchant_normalized", "amount", "transaction_date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_account_date",
        "transactions",
        ["user_id", "account_id", "transaction_date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_category_date",
        "transactions",
        ["user_id", "category_id", "transaction_date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_date", "transactions", ["user_id", "transaction_date"], unique=False
    )
    op.create_index(
        "ix_transactions_user_due", "transactions", ["user_id", "due_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_user_due", table_name="transactions")
    op.drop_index("ix_transactions_user_date", table_name="transactions")
    op.drop_index("ix_transactions_user_category_date", table_name="transactions")
    op.drop_index("ix_transactions_user_account_date", table_name="transactions")
    op.drop_index("ix_transactions_dedup", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
    bind = op.get_bind()
    for enum_name in (
        "account_type",
        "category_kind",
        "essentiality",
        "transaction_type",
        "transaction_status",
        "transaction_source",
        "payment_method",
        "transfer_direction",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
