"""Add documents and extracted_items tables

Revision ID: 5aa971b2238a
Revises: 71f63885b599
Create Date: 2026-09-19 17:41:14.526068
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5aa971b2238a'
down_revision: str | None = '71f63885b599'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'xml', 'json', 'png', 'jpeg', name='document_type'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('processing_status', sa.Enum('uploaded', 'processing', 'awaiting_confirmation', 'confirmed', 'failed', 'rejected', name='processing_status'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_hash', name='uq_document_hash')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('extracted_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_of_transaction_id', sa.UUID(), nullable=True),
    sa.Column('duplicate_reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', 'edited_confirmed', name='extracted_item_status'), nullable=False),
    sa.Column('created_transaction_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_items_document_id'), 'extracted_items', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_items_user_id'), 'extracted_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_items_user_id'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_document_id'), table_name='extracted_items')
    op.drop_table('extracted_items')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
